### PR TITLE
Updated struct type variable names to reflect upstream changes

### PR DESCRIPTION
**Pull request by electricWah**
I haven't been able to test it on a calculator yet, but with these changes it fully compiles so it probably works

### CODE REVIEW

**Comment by adriweb** [comment]
But it did compile just fine earlier this year and I don't believe any upstream change made these  necessary... I'll try again with the latest toolchain just in case.

**Comment by electricWah** [comment]
The change I was referencing was this: https://github.com/CE-Programming/toolchain/pull/428/

I guess it's not technically an upstream change if the variables names hadn't existed yet...oh well

I was getting this error: `src/bindings/graphx.c:76:5: fatal error: incomplete definition of type 'struct _gfx_sprite_t'` 
I tried to replace all the changed variable names from `_name_t` to `name_t` but it looks like something went wrong and I changed a bunch of unnecessary stuff. I was able to test the compiled app today and it glitched out, so that may be why.

**Comment by electricWah** [comment]
it appears these are the only names that need the leading underscore removed: 
```
_cplx_t
_gfx_sprite_t
_real_t
```

**Comment by adriweb** [comment]
Alright so I just tried a build with the latest master of the toolchain, and it worked just fine (compiling and linking).
But ! It turned out I had uncommitted changes on my side (regarding what you've mentioned, precisely), so I've now forced-pushed the branch to fix it.

I also updated the "light" branch since that's also useful...

Thanks!

**Pull request closed without merging**
